name: Xolayhaber Bot

on:
  workflow_dispatch:

jobs:
  calistir:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Repo indir
        uses: actions/checkout@v3

      - name: Basit test
        run: echo "WORKFLOW CALISTI"

      - name: Python kontrol
        run: python --version

      - name: main.py çalıştır
        run: python main.py
