name: Xolayhaber Bot

on:
  schedule:
    - cron: "0 */6 * * *"   # 6 saatte bir çalışır
  workflow_dispatch:       # Manuel çalıştırma da mümkün

jobs:
  calistir:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları indir
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri yükle
        run: pip install -r requirements.txt

      - name: Botu çalıştır
        run: python main.py
