name: Xolayhaber Bot

on:
  workflow_dispatch:

jobs:
  calistir:
    runs-on: ubuntu-latest

    steps:
      - name: Repo indir
        uses: actions/checkout@v3

      - name: Dosyaları listele
        run: ls -la

      - name: Python versiyon
        run: python --version

      - name: main.py çalıştır
        run: python main.py
